### ISSUE TITLE
Remove Timber dependency

### ISSUE THREAD

**Issue by sergeich** [dailymotion/dailymotion-player-sdk-android#61]
Timber dependency required to be added to the application now. It's not included in library but is used inside it.

Either include it in the library or remove the usage.

**Comment by martinbonnin** [comment]
Can you elaborate on places where this doesn't work ? Gradle should detect the transitive dependency and add it to your app automatically. Or do I miss something ?

**Comment by sergeich** [comment]
>Gradle should detect the transitive dependency and add it to your app automatically.

Looks like gradle doesn't add it automatically now.

I've [forked the repository](https://github.com/sergeich/dailymotion-player-sdk-android), removed SDK source code and replaced it with gradle dependency.
It compiles and run, but crashes immediately
1. It requires `play-services-ads` and `gson` libraries to be added to the app dependencies. Didn't notice it first time because they are already used in my app.
2. It requires Timber library to be added, even if it's not used in the client app.

```
2018-12-19 16:13:00.296 27301-27301/com.dailymotion.websdksample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dailymotion.websdksample, PID: 27301
    java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber;
        at com.dailymotion.android.player.sdk.PlayerWebView.handleEvent(PlayerWebView.java:296)
        at com.dailymotion.android.player.sdk.PlayerWebView.access$000(PlayerWebView.java:45)
        at com.dailymotion.android.player.sdk.PlayerWebView$JavascriptBridge$1.run(PlayerWebView.java:233)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "timber.log.Timber" on path: DexPathList[[zip file "/data/app/com.dailymotion.websdksample-Cq9iY9GU2omsINulWTy60w==/base.apk"],nativeLibraryDirectories=[/data/app/com.dailymotion.websdksample-Cq9iY9GU2omsINulWTy60w==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.dailymotion.android.player.sdk.PlayerWebView.handleEvent(PlayerWebView.java:296) 
        at com.dailymotion.android.player.sdk.PlayerWebView.access$000(PlayerWebView.java:45) 
        at com.dailymotion.android.player.sdk.PlayerWebView$JavascriptBridge$1.run(PlayerWebView.java:233) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6680) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by martinbonnin** [comment]
Thanks for the fork. I can confirm the crash. I'll look into this.

**Comment by martinbonnin** [comment]
Somehow the pom file in jcenter was missing dependencies. I just uploaded a new version that should have them. Can you try with v0.1.27 ?

**Comment by sergeich** [comment]
Checked.
Yes, everything ok now.
Thank you!
