### ISSUE TITLE
Crash on shouldOverrideUrlLoading Intent not found activity to execute. 

### ISSUE THREAD

**Issue by DragonJ-GAO** [dailymotion/dailymotion-player-sdk-android#95]
{noformat}
android.content.ActivityNotFoundException: 
  at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2007)
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1673)
  at android.app.Activity.startActivityForResult (Activity.java:4586)
  at androidx.fragment.app.FragmentActivity.startActivityForResult (FragmentActivity.java:675)
  at android.app.Activity.startActivityForResult (Activity.java:4544)
  at androidx.fragment.app.FragmentActivity.startActivityForResult (FragmentActivity.java:662)
  at android.app.Activity.startActivity (Activity.java:4905)
  at android.app.Activity.startActivity (Activity.java:4873)
  at com.dailymotion.android.player.sdk.PlayerWebView$finishInitialization$1.shouldOverrideUrlLoading (PlayerWebView.java:235)
  at android.webkit.WebViewClient.shouldOverrideUrlLoading (WebViewClient.java:77)
  at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading (AwContentsClientBridge.java:16)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:326)
  at android.os.Looper.loop (Looper.java:160)
  at android.app.ActivityThread.main (ActivityThread.java:6758)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:497)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:912)
{noformat}

**Comment by Helmt89** [comment]
I have the same issue

Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=data:text/html;charset=utf-8,<html></html> flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
       at android.app.Activity.startActivityForResult(Activity.java:4689)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:4647)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:5008)
       at android.app.Activity.startActivity(Activity.java:4976)
       at com.dailymotion.android.player.sdk.PlayerWebView$finishInitialization$1.shouldOverrideUrlLoading(PlayerWebView.java:227)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:15)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by geoffreytan** [comment]
Hi 👋

I believe was crash was fixed from v0.2.5 (included) and should not happen anymore.
Can you tell me which version you are running?

**Comment by Helmt89** [comment]
This is good news. We will try new version.
